alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
name: bugpile-app
region: tor
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: benvvalk/bugpile
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: bugpile-web
  source_dir: /
  run_command: ./manage.py makemigrations && ./manage.py migrate && ./manage.py collectstatic --no-input && gunicorn --worker-tmp-dir /dev/shm bugpile.wsgi
  envs:
    - key: DJANGO_DEBUG
      value: 'False'
      scope: RUN_TIME
    - key: DJANGO_ALLOWED_HOSTS
      value: bugpile-app-yvkdq.ondigitalocean.app,bugpile.net
      scope: RUN_TIME
